# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t spring-cicd .
          docker tag spring-cicd wish2rich/spring-cicd:${GITHUB_SHA::7}
          docker push wish2rich/spring-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-35-20-96.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          scripts: |
            docker pull wish2rich/spring-cicd:${GITHUB_SHA::7}
            docker tag wish2rich/spring-cicd:${GITHUB_SHA::7} spring-cicd
            docker stop erver
            docker run -d --rm --name server -p 80:8080 spring-cicd
